export const GET_CHATROOMS = "GET_CHATROOMS";
export const DELETE_CHATROOM = "DELETE_CHATROOM";
export const ADD_CHATROOM = "ADD_CHATROOM";
export const GET_USER_BY_TOKEN = "GET_USER_BY_TOKEN";
export const RETURN_USER_AND_TOKEN = "RETURN_USER_AND_TOKEN";