# Generated by Django 2.2.6 on 2019-12-03 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20191203_1006'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('knox', '0007_auto_20190111_0542'),
        ('friends', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
